stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/raw/200k_Restaurants_Mostly_US.csv
    params:
      - prepare.raw_input_path
      - prepare.test_size
      - prepare.seed
    outs:
      - data/processed/train.parquet
      - data/processed/test.parquet

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.parquet
    params:
      - train.n_estimators
      - train.max_depth
      - train.model_path
    outs:
      - models/restaurant_classifier.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/restaurant_classifier.pkl
      - data/processed/test.parquet
    metrics:
      - metrics.json:
          cache: false